### ISSUE TITLE
Why not return Self in most methods?

### ISSUE THREAD

**Issue by mkll** [Pimine/EasySwiftLayout#10]
Hi there. Thanks for the great library, I'm happy to use it in almost all of my Swift projects.
But I discovered that in recent releases most methods don't return `Self` anymore. Why? It was very convenient for chaining method calls.

**Comment by denandreychuk** [comment]
Hi! Thanks for your questions. This will be added in the next release. I noticed it too, but for some reasons I didn't add it for now.

**Comment by mkll** [comment]
Thanks! Awaiting for the next release.

**Comment by denandreychuk** [comment]
@mkll feel free to checkout the latest release:)

**Comment by mkll** [comment]
@denandreychuk Oh, you did not let me wait to one's heart's content :) Thanks!
