### ISSUE TITLE
Ambiguous use of 'size'

### ISSUE THREAD

**Issue by BayramInanc** [Pimine/EasySwiftLayout#20]
<img width="978" alt="Ekran Resmi 2022-08-29 02 41 30" src="https://user-images.githubusercontent.com/12694849/187099511-d2e72caa-1a47-4f5e-b40f-18f13429635e.png">

**Comment by denandreychuk** [comment]
Hey @BayramInanc, I'll try to fix it in the next release. Thanks for your issue:)

**Comment by denandreychuk** [comment]
Fixed in https://github.com/Pimine/EasySwiftLayout/pull/21
